# -*- coding: utf-8 -*-
"""DeepLearningonCSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19QNwe8SoxN1pCeXRJcdtZmBlYGB1SyPv
"""

import pandas as pd
x=pd.read_csv("9db113a1-cdbe-4b1c-98c2-11590f124dd8.csv")
y=pd.read_csv("5c9fa979-5a84-45d6-93b9-543d1a0efc41.csv")

x.head()

x=x.iloc[1:]

x=x.iloc[:,1:]

z=x.iloc[:,4]

x=x.iloc[:,:4]

x.head()

m=y.iloc[:,1:]

x=x.append(m,ignore_index=True)

x

import keras
from keras import metrics
from keras import regularizers
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.optimizers import Adam, RMSprop
from keras.callbacks import TensorBoard, EarlyStopping, ModelCheckpoint
from keras.utils import plot_model
from keras.callbacks import EarlyStopping

t_model = Sequential()
t_model.add(Dense(10000, activation="relu", input_shape=(4,)))
t_model.add(Dense(10000, activation="relu"))
t_model.add(Dense(1))
t_model.compile(
    loss="mean_squared_error",
    optimizer=Adam(lr=0.001),
    metrics=[metrics.mae])
early_stopping_monitor = EarlyStopping(patience=3)

epochs = 500
t_model.fit(x.iloc[:575,:], z, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

